//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeCompany.MySQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public string ProductName { get; set; }
        public string ApprovedByUser { get; set; }
        public decimal Price { get; set; }
        public int NumberOfOrders { get; set; }
        public decimal TotalRevenue { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
    }
}
